### ISSUE TITLE
question regarding the paper

### ISSUE THREAD

**Issue by xyy-ict** [Wang-ML-Lab/GRDA#3]
May I pose a question regarding the paper? What sets apart Corollary 4.1 from Corollary 4.3? It appears that in Corollary 4.1, achieving the global optimum necessitates uniform alignment, whereas in Corollary 4.3, it does not (the uniform alignment is relaxed).

Corollary 4.1. For GRDA, the global optimum of total loss Ld(D, E) is achieved if the encoding of all domains (indexed by u) are perfectly (uniformly) aligned, i.e., e ⊥ u. 
Corollary 4.3 (Star Graphs). In a star graph, the GRDA optimum is achieved if and only if the embedding distribution of the center domain is the average of all peripheral domains.

**Comment by shsjxzh** [comment]
Hi xyy-ict,

I want to emphasize that the global optimum doesn't necessitate uniform alignment. Corollary 4.1 states that uniform alignment is one of the possible ways to achieve the global optimum of GRDA. This means our model generalizes DANN, because any global optima achieved by DANN (uniform alignment) would also be global optima of GRDA. However, the global optima of GRDA can be achieved by alignments other than uniform alignment.

In Corollary 4.3, we analyze a special kind of graph. It exemplifies that uniform alignment is one of the alignments to achieve global optimum. That is, uniform alignment is a special case of "embedding distribution of the center domain is the average of all peripheral domains"

**Comment by xyy-ict** [comment]
Got it. Thanks so much again.

**Comment by shsjxzh** [comment]
You are welcome.
